### ISSUE TITLE
Multiple generation of the same tag.

### ISSUE THREAD

**Issue by abekkine** [taigh/sublime-tagify#5]
If a file containing a tag is open in a tab, tags in this file reported twice.

Observed on 
Sublime Text 3, Build 3083,
Ubuntu 14.04.2 LTS, Desktop Edition,
Linux3.13.0-46-generic #79-Ubuntu SMP x86_64 GNU/Linux

**Comment by taigh** [comment]
fixed in b3673a1f2e729190d5bb5478c10a6c0dd5248776, thanks
